Add -Djava.awt.headless=true

diff --git a/.github/workflows/native-image.yml b/.github/workflows/native-image.yml
--- a/.github/workflows/native-image.yml
+++ b/.github/workflows/native-image.yml
@@ -50,15 +50,15 @@ jobs:
       - name: Generate GraalVM configuration
         run: |
           mkdir native-image-config-dir
-          echo 'Bob->Alice: Hello' | java -agentlib:native-image-agent=config-output-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tpng -pipe
-          echo 'Bob->Alice: Hello' | java -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tpdf -pipe
-          echo 'Bob->Alice: Hello' | java -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -ttxt -pipe
-          echo 'Bob->Alice: Hello' | java -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tuxt -pipe
-          echo 'Bob->Alice: Hello' | java -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tsvg -pipe -theme minty
-          echo 'help themes' | java -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tsvg -pipe
-          echo 'error' | java -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tsvg -pipe > out.svg || true
-          printf '!include <C4/C4_Context>\n\ntitle System Context diagram for Internet Banking System\n\nPerson(customer, "Banking Customer", "A customer of the bank, with personal bank accounts.")\n\nSystem(banking_system, "Internet Banking System", "Allows customers to check their accounts.")\n\nSystem_Ext(mail_system, "E-mail system", "The internal Microsoft Exchange e-mail system.")\nSystem_Ext(mainframe, "Mainframe Banking System", "Stores all of the core banking information.")\n\nRel(customer, banking_system, "Uses")\nRel_Back(customer, mail_system, "Sends e-mails to")\nRel_Neighbor(banking_system, mail_system, "Sends e-mails", "SMTP")\nRel(banking_system, mainframe, "Uses")' | java -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tpdf -pipe
-          printf '!include <archimate/Archimate>\n\ntitle Archimate Sample - Internet Browser\n\nBusiness_Object(businessObject, \"A Business Object\")' | java -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tsvg -pipe
+          echo 'Bob->Alice: Hello' | java -Djava.awt.headless=true -agentlib:native-image-agent=config-output-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tpng -pipe
+          echo 'Bob->Alice: Hello' | java -Djava.awt.headless=true -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tpdf -pipe
+          echo 'Bob->Alice: Hello' | java -Djava.awt.headless=true -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -ttxt -pipe
+          echo 'Bob->Alice: Hello' | java -Djava.awt.headless=true -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tuxt -pipe
+          echo 'Bob->Alice: Hello' | java -Djava.awt.headless=true -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tsvg -pipe -theme minty
+          echo 'help themes' | java -Djava.awt.headless=true -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tsvg -pipe
+          echo 'error' | java -Djava.awt.headless=true -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tsvg -pipe > out.svg || true
+          printf '!include <C4/C4_Context>\n\ntitle System Context diagram for Internet Banking System\n\nPerson(customer, "Banking Customer", "A customer of the bank, with personal bank accounts.")\n\nSystem(banking_system, "Internet Banking System", "Allows customers to check their accounts.")\n\nSystem_Ext(mail_system, "E-mail system", "The internal Microsoft Exchange e-mail system.")\nSystem_Ext(mainframe, "Mainframe Banking System", "Stores all of the core banking information.")\n\nRel(customer, banking_system, "Uses")\nRel_Back(customer, mail_system, "Sends e-mails to")\nRel_Neighbor(banking_system, mail_system, "Sends e-mails", "SMTP")\nRel(banking_system, mainframe, "Uses")' | java -Djava.awt.headless=true -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tpdf -pipe
+          printf '!include <archimate/Archimate>\n\ntitle Archimate Sample - Internet Browser\n\nBusiness_Object(businessObject, \"A Business Object\")' | java -Djava.awt.headless=true -agentlib:native-image-agent=config-merge-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tsvg -pipe
 
       - name: Generate native image
         run: |
