Run PlantUML on an invalid diagram to prepare the native image

diff --git a/.github/workflows/native-image.yml b/.github/workflows/native-image.yml
--- a/.github/workflows/native-image.yml
+++ b/.github/workflows/native-image.yml
@@ -52,6 +52,7 @@ jobs:
           mkdir native-image-config-dir
           echo 'Bob->Alice: Hello' | java -agentlib:native-image-agent=config-output-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tpng -pipe > out.png
           echo 'Bob->Alice: Hello' | java -agentlib:native-image-agent=config-output-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tpdf -pipe > out.pdf
+          echo 'error' | java -agentlib:native-image-agent=config-output-dir=native-image-config-dir -jar "./build/libs/plantuml-pdf-${{ inputs.release-version }}.jar" -tsvg -pipe > out.svg || true
 
       - name: Generate native image
         run: |
